name: sync-from-coding-devops
on:
  schedule:
    # 早晚10点各同步一次
    - cron: "0 10,22 * * *"
  # https://docs.github.com/cn/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@e.coding.net/quanttide/qtopen-python/qcloud-sdk-py.git
          source_branch: master
          destination_branch: master
          github_token: ${{ secrets.PAT }}
          # 同步Coding仓库标签，在GitHub手动发布
          sync_tags: true
